### ISSUE TITLE
Issue loading pyet.so

### ISSUE THREAD

**Issue by terrybr** [Ododo/Pyet3#1]
Hi,

I've been trying to install Pyet3, but I'm getting those errors:

![errors ](https://user-images.githubusercontent.com/378788/64987031-4ec8fe80-d896-11e9-93a9-5a59cce8fc43.png)

The file pyet.so is in the correct directory with the right permissions, yet it says it can't find it.

Thank you for any help you can provide.

**Comment by Ododo** [comment]
Hello @terrybr , thank you for your interest in this Project.

There must me a issue with how Pyet constructs the path to pyet.so.
But this is not the only issue: even if you succeed to load pyet.so, it's most likely you won't be able to link it with python and boost/python because the librairies are not included in the release and the version used at the time are really old.
However, i was planning to release a workable version with shipped libraries and some fixes like the one you are dealing with. I will have some time in october to do this, and i come back to you.

Sorry for the inconvenience.

**Comment by terrybr** [comment]
Hi @Ododo,

Thank you for your response.  Looking forward to it! :)

Cheers!

**Comment by Ododo** [comment]
Hello @terrybr . I'm very sorry i did not find the time to work on that project. :( I'm starting a rework of pyet3 based on cffi which will be easier to work with. very few things implemented at the moment.. but If you are still interested in that,  you can check out the default branch of the project that should point to pyet3-cffi now.
